### ISSUE TITLE
whitelist not working as expected

### ISSUE THREAD

**Issue by xuhanz** [patrick-sharp/UserAnalytics#19]
User Analytics version: (latest version on the main branch)

Operating system: Windows

Issue:  After I add "www.amazon.com" to "Do-Not-Track List", the time for amazon in the timesheet is still increasing

Console Error (including full traceback):
Command or request that led to error and steps to reproduce:
I could reproduce the error on my Chrome.  (1) Unpack & Install the extension (2) go to the dashboard and click on "Save" (3) open up amazon.com and browse a little bit (4) refresh the dashboard

**Comment by YukaiYan** [comment]
At this point, we are only tracking domains, please use the proper format (i.e. **amazon.com** instead of **www.amazon.com**)
