### ISSUE TITLE
Toggle tracking does not sync between popup and dashboard settings

### ISSUE THREAD

**Issue by laksh-g** [patrick-sharp/UserAnalytics#20]
User Analytics version: (latest version on the main branch commit no - 5d7271d8a85e494919fb432ce53a5eeee0de5b2d) 

Operating system: Windows

Issue: After toggling tracking to OFF on the extension popup, the settings do not sync on the dashboard settings page, it still shows as tracking ON.

Console Error (including full traceback): No Console Error
Command or request that led to error and steps to reproduce:
(1) Go to any website and open up the extension popup
(2) Toggle tracking to OFF
(3) click on the "Go to Dashboard"
(4) Click on settings cog and the option to turn off tracking remains unchecked.

**Comment by YukaiYan** [comment]
Dashboard redesigned, removed tracking option on the dashboard.
